# Generated by Django 4.2.16 on 2025-06-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата календаря', unique=True, verbose_name='Дата')),
                ('is_working_day', models.BooleanField(default=True, help_text='Является ли день рабочим', verbose_name='Рабочий день')),
                ('description', models.CharField(blank=True, help_text='Описание (например, название праздника)', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Календарь рабочих дней',
                'verbose_name_plural': 'Календарь рабочих дней',
                'db_table': 'working_calendar',
                'ordering': ['date'],
            },
        ),
    ]
