# Generated by Django 4.2.16 on 2025-06-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_remove_flow_estimated_duration_hours_and_more"),
        ("guides", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="flow_step",
            field=models.OneToOneField(
                blank=True,
                help_text="Связанный этап потока",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article",
                to="flows.flowstep",
                verbose_name="Этап потока",
            ),
        ),
    ]
