# Generated by Django 4.2.16 on 2025-06-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email пользователя (устаревшее поле)', max_length=254, null=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(help_text='Уникальный ID пользователя в Telegram (основной идентификатор)', max_length=50, unique=True, verbose_name='Telegram ID'),
        ),
    ]
