# Generated by Django 4.2.16 on 2025-06-14 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_flows', to=settings.AUTH_USER_MODEL, verbose_name='Приостановил'),
        ),
        migrations.AddField(
            model_name='userflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flows', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tasksnapshot',
            name='user_step_progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_snapshot', to='flows.userstepprogress', verbose_name='Прогресс по этапу'),
        ),
        migrations.AddField(
            model_name='task',
            name='flow_step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='flows.flowstep', verbose_name='Этап потока'),
        ),
        migrations.AddField(
            model_name='quizsnapshot',
            name='user_step_progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_snapshot', to='flows.userstepprogress', verbose_name='Прогресс по этапу'),
        ),
        migrations.AddField(
            model_name='quizquestionsnapshot',
            name='quiz_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flows.quizsnapshot', verbose_name='Снапшот квиза'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flows.quiz', verbose_name='Квиз'),
        ),
        migrations.AddField(
            model_name='quizanswersnapshot',
            name='question_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='flows.quizquestionsnapshot', verbose_name='Снапшот вопроса'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='flows.quizquestion', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='flow_step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='flows.flowstep', verbose_name='Этап потока'),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_steps', to='guides.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_steps', to='flows.flow', verbose_name='Поток'),
        ),
        migrations.AddField(
            model_name='flowbuddy',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buddy_flows', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='flowbuddy',
            name='buddy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_flows', to=settings.AUTH_USER_MODEL, verbose_name='Бадди'),
        ),
        migrations.AddField(
            model_name='flowbuddy',
            name='user_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_buddies', to='flows.userflow', verbose_name='Прохождение потока'),
        ),
        migrations.AddField(
            model_name='flowaction',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_flow_actions', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил'),
        ),
        migrations.AddField(
            model_name='flowaction',
            name='user_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='flows.userflow', verbose_name='Прохождение потока'),
        ),
        migrations.AddIndex(
            model_name='userstepprogress',
            index=models.Index(fields=['user_flow', 'status'], name='user_step_p_user_fl_736846_idx'),
        ),
        migrations.AddIndex(
            model_name='userstepprogress',
            index=models.Index(fields=['flow_step', 'status'], name='user_step_p_flow_st_ccb3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstepprogress',
            unique_together={('user_flow', 'flow_step')},
        ),
        migrations.AlterUniqueTogether(
            name='userquizanswersnapshot',
            unique_together={('quiz_snapshot', 'question_snapshot')},
        ),
        migrations.AddIndex(
            model_name='userquizanswer',
            index=models.Index(fields=['user_flow', 'is_correct'], name='user_quiz_a_user_fl_863733_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizanswer',
            index=models.Index(fields=['question', 'is_correct'], name='user_quiz_a_questio_fa8ddd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userquizanswer',
            unique_together={('user_flow', 'question')},
        ),
        migrations.AddIndex(
            model_name='userflow',
            index=models.Index(fields=['user', 'status'], name='user_flows_user_id_0b8b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='userflow',
            index=models.Index(fields=['flow', 'status'], name='user_flows_flow_id_4a883b_idx'),
        ),
        migrations.AddIndex(
            model_name='userflow',
            index=models.Index(fields=['expected_completion_date'], name='user_flows_expecte_31d423_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userflow',
            unique_together={('user', 'flow')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='flowstep',
            unique_together={('flow', 'order')},
        ),
        migrations.AddIndex(
            model_name='flowbuddy',
            index=models.Index(fields=['buddy_user', 'is_active'], name='flow_buddie_buddy_u_c67a40_idx'),
        ),
        migrations.AddIndex(
            model_name='flowbuddy',
            index=models.Index(fields=['user_flow', 'is_active'], name='flow_buddie_user_fl_ec81a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowbuddy',
            unique_together={('user_flow', 'buddy_user')},
        ),
        migrations.AddIndex(
            model_name='flowaction',
            index=models.Index(fields=['user_flow', 'action_type'], name='flow_action_user_fl_ffceba_idx'),
        ),
        migrations.AddIndex(
            model_name='flowaction',
            index=models.Index(fields=['performed_by', 'performed_at'], name='flow_action_perform_b0d228_idx'),
        ),
    ]
