# Generated by Django 4.2.16 on 2025-06-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="estimated_duration_hours",
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="article",
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="estimated_time_minutes",
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="is_required",
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="step_type",
        ),
    ]
