# Generated by Django 4.2.16 on 2025-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksnapshot",
            name="task_hint",
            field=models.TextField(blank=True, null=True, verbose_name="Подсказка"),
        ),
        migrations.AlterField(
            model_name="tasksnapshot",
            name="task_instruction",
            field=models.TextField(blank=True, null=True, verbose_name="Инструкция"),
        ),
    ]
